from envparse import env

STEPIK_BASE_URL = env('STEPIK_BASE_URL')
STEPIK_CLIENT_ID = env('STEPIK_CLIENT_ID')
STEPIK_CLIENT_SECRET = env('STEPIK_CLIENT_SECRET')

WIKI_LOGIN = env('WIKI_LOGIN')
WIKI_PASSWORD = env('WIKI_PASSWORD')
WIKI_BASE_URL = env('WIKI_BASE_URL')
WIKI_API_PATH = env('WIKI_API_PATH', default='/api.php')

UPLOAD_CARE_PUB_KEY = env('UPLOAD_CARE_PUB_KEY')
YANDEX_SPEECH_KIT_KEY = env('YANDEX_SPEECH_KIT_KEY')
