from envparse import env

STEPIK_CLIENT_ID = env('STEPIK_CLIENT_ID')
STEPIK_CLIENT_SECRET = env('STEPIK_CLIENT_SECRET')
UPLOAD_CARE_PUB_KEY = env('UPLOAD_CARE_PUB_KEY')
YANDEX_SPEECH_KIT_KEY = env('YANDEX_SPEECH_KIT_KEY')

WIKI_LOGIN = env('WIKI_LOGIN')
WIKI_PASSWORD = env('WIKI_PASSWORD')
