FRAME_PERIOD = 3
BOTTOM_LINE_COEF = 3

TIME_BETWEEN_KEYFRAMES = 4
THRESHOLD_FOR_PEAKS_DETECTION = 0.08
THRESHOLD_DELTA = 0.02
MAX_KEYFRAME_PER_MIN = 4
MAX_KEYFRAME_PER_SEC = MAX_KEYFRAME_PER_MIN / 60

SCALE_FACTOR = 1.05
MIN_SIZE_COEF = 5

CENTER_LEFT_BORDER = 0.4
CENTER_RIGHT_BORDER = 0.6

UPLOADCARE_URL_TO_UPLOAD = 'https://upload.uploadcare.com/base/'
